In [2]:
import pandas as pd

In [6]:
data={"name":["Alice","Bob"],"Age":[25,30]}
df=pd.DataFrame(data)
df

    name  Age
0  Alice   25
1    Bob   30

In [5]:
lst=[["Alice",25],["Bob",30]]
df=pd.DataFrame(lst,columns=["Name","Age"])
df

    Name  Age
0  Alice   25
1    Bob   30

In [ ]:
df.head()

    name  Age
0  Alice   25
1    Bob   30

In [8]:
df.tail()

    name  Age
0  Alice   25
1    Bob   30

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    2 non-null      str
 1   Age     2 non-null      int64
dtypes: int64(1), str(1)
memory usage: 164.0 bytes

In [10]:
df.describe()

             Age
count   2.000000
mean   27.500000
std     3.535534
min    25.000000
25%    26.250000
50%    27.500000
75%    28.750000
max    30.000000

In [13]:
df["name"]

0    Alice
1      Bob
Name: name, dtype: str

In [14]:
df[["name","Age"]]

    name  Age
0  Alice   25
1    Bob   30

In [15]:
df.loc[0]

name    Alice
Age        25
Name: 0, dtype: object

In [16]:
df.iloc[1]

name    Bob
Age      30
Name: 1, dtype: object

In [17]:
df[df["Age"]>25]

  name  Age
1  Bob   30

In [18]:
df["Gender"]=["F","M"]

In [19]:
df.drop("Age",axis=1,inplace=True)

In [20]:
df.isnull()

    name  Gender
0  False   False
1  False   False

In [21]:
df.dropna()

    name Gender
0  Alice      F
1    Bob      M

In [22]:
df.fillna(0)

    name Gender
0  Alice      F
1    Bob      M

In [24]:
data1={"name":["Abhin","Aravind"],"Age":[20,19]}
df1=pd.DataFrame(data1)
data2={"name":["Mahima","Mahesh"],"Age":[20,50]}
df2=pd.DataFrame(data2)